title: Owen's Website
email: me@odaigle.xyz
logo: /images/tief.jpg
description: >- # this means to ignore newlines until "baseurl:"
  My name is Owen Daigle, a linux user who is attending the University of Ottawa in Computer Engineering. I enjoy working with computer software/hardware, self hosting my own services on my personal servers, and learning about rechargeable batteries. Or really anything to do with computers :-)
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: jekyll-theme-minimal
plugins:
  - jekyll-feed


# variables
legacy-site-location: old