---
# Homepage configuration
# See https://fontawesome.com/v5/search for icons options

# Optional: Use external configuration file.
# Using this will ignore remaining config in this file
# externalConfig: https://example.com/server-luci/config.yaml

title: "Owen Daigle's Dashboard"
subtitle: ""
# documentTitle: "Welcome" # Customize the browser tab text
logo: "../1mainResources/tief"
# Alternatively a fa icon can be provided:
# icon: "fas fa-skull-crossbones"

header: true # Set to false to hide the header
# Optional: Different hotkey for search, defaults to "/"
# hotkey:
#   search: "Shift"
footer: 'Forked from <a href="https://github.com/bastienwirtz/homer"><i class="fab fa-github-alt"></i></a></p>' # set false if you want to hide it.

columns: "3" # "auto" or number (must be a factor of 12: 1, 2, 3, 4, 6, 12)
connectivityCheck: false # whether you want to display a message when the apps are not accessible anymore (VPN disconnected for example).
                        # You should set it to true when using an authentication proxy, it also reloads the page when a redirection is detected when checking connectivity.

# Optional: Proxy / hosting option
proxy:
  useCredentials: false # send cookies & authorization headers when fetching service specific data. Set to `true` if you use an authentication proxy. Can be overrided on service level.

# Set the default layout and color scheme
defaults:
  layout: columns # Either 'columns', or 'list'
  colorTheme: auto # One of 'auto', 'light', or 'dark'

# Optional theming
theme: default # 'default' or one of the themes available in 'src/assets/themes'.

# Optional custom stylesheet
# Will load custom CSS files. Especially useful for custom icon sets.
# stylesheet:
#   - "assets/custom.css"

# Here is the exhaustive list of customization parameters
# However all value are optional and will fallback to default if not set.
# if you want to change only some of the colors, feel free to remove all unused key.
colors:
  light:
    highlight-primary: "#ff7914"
    highlight-secondary: "#fb852c"
    highlight-hover: "#fb852c"
    background: "#f5f5f5"
    card-background: "#ffffff"
    text: "#363636"
    text-header: "#424242"
    text-title: "#303030"
    text-subtitle: "#424242"
    card-shadow: rgba(0, 0, 0, 0.1)
    link: "#3273dc"
    link-hover: "#363636"
    background-image: "assets/your/light/bg.png"
  dark:
    highlight-primary: "#ff7914"
    highlight-secondary: "#fb852c"
    highlight-hover: "#fb852c"
    background: "#131313"
    card-background: "#2b2b2b"
    text: "#eaeaea"
    text-header: "#ffffff"
    text-title: "#fafafa"
    text-subtitle: "#f5f5f5"
    card-shadow: rgba(0, 0, 0, 0.4)
    link: "#3273dc"
    link-hover: "#ffdd57"
    background-image: "assets/your/dark/bg.png"

# Optional message
message:
  # url: "https://<my-api-endpoint>" # Can fetch information from an endpoint to override value below.
  # mapping: # allows to map fields from the remote format to the one expected by Homer
  #   title: 'id' # use value from field 'id' as title
  #   content: 'value' # value from field 'value' as content
  # refreshInterval: 10000 # Optional: time interval to refresh message
  #
  # Real example using chucknorris.io for showing Chuck Norris facts as messages:
  # url: https://api.chucknorris.io/jokes/random
  # mapping:
  #   title: 'id'
  #   content: 'value'
  # refreshInterval: 10000
  style: "is-warning"
  title: "Under Construction"
  icon: "fa fa-exclamation-triangle"
  content: "Website under construction. Downtime and changes expected."

# Optional navbar
# links: [] # Allows for navbar (dark mode, layout, and search) without any links
links:
  - name: "Main Site"
    icon: ""
    url: "https://www.odaigle.xyz"
    target: "" # optional html tag target attribute
    # this will link to a second homer page that will load config from page2.yml and keep default config values as in config.yml file
  # see url field and assets/page.yml used in this example:

# Services
# First level array represents a group.
# Leave only a "items" key if not using group (group name, icon & tagstyle are optional, section separation will not be displayed).
services:
  - name: "Application"
    icon: ""
    # A path to an image can also be provided. Note that icon take precedence if both icon and logo are set.
    # logo: "path/to/logo"
    items:
      - name: "Jellyfin"
        logo: "assets/icons/jellyfin.png"
        # Alternatively a fa icon can be provided:
        # icon: "fab fa-jenkins"
        subtitle: "Media Streaming"
        tag: "app"
        keywords: "movies shows tv jelly" # optional keyword used for searching purpose
        url: "https://jellyfin.odaigle.xyz"
        target: "" # optional html tag target attribute
      - name: "Nextcloud"
        logo: "assets/icons/nextcloud.png"
        subtitle: "File Storage"
        tag: "app"
        keywords: "files storage nextcloud nc"
        url: "https://nc.odaigle.xyz"
      - name: "Plex"
        logo: "assets/icons/plex.png"
        subtitle: "Media Streaming"
        tag: "app"
        keywords: "plex movies shows tv"
        url: "https://app.plex.tv"
      - name: "Stirling PDF"
        logo: "assets/icons/pdf.png"
        subtitle: "PDF Tools"
        tag: "app"
        keywords: "pdf document" # optional keyword used for searching purpose
        url: "https://pdf.odaigle.xyz"
  - name: "Games"
    icon: ""
    items:
      - name: "Minecraft Survival World Map"
        logo: "assets/icons/mc.png"
        subtitle: "mcmap1"
        tag: "game"
        keywords: "minecraft survival" # optional keyword used for searching purpose
        url: "https://mcmap1.odaigle.xyz"
      - name: "Minecraft Creative World Map"
        logo: "assets/icons/mc.png"
        subtitle: "mcmap2"
        tag: "game"
        keywords: "minecraft creative" # optional keyword used for searching purpose
        url: "https://mcmap2.odaigle.xyz"
  - name: "LAN Only"
    icon: ""
    items:
      - name: "Requests"
        logo: ""
        subtitle: "Media Requests"
        tag: "game"
        keywords: "minecraft survival" # optional keyword used for searching purpose
        url: "http://192.168.50.11"
